export const materialData = [
    {
       materialNo:"B851-001889",
       description:"POWER STEERING FLUID 1888 CALTEX",
       plant:"PLANT 1",
       andonDisplay:"POWER STEERING",
       depthMaterial:"93",
       supplyLine: "ASSY-MEZANINE",
       uom:"Liter",
       createdBy: "user1",
       createdDate: "16 Nov 2024",
       changedBy: "",
       changedDate: "",
    },
    {
       materialNo:"",
       description:"",
       plant:"",
       andonDisplay:"",
       depthMaterial:"",
       supplyLine: "",
       uom:"",
       createdBy: "",
       createdDate: "",
       changedBy: "",
       changedDate: "",
    },
    {
       materialNo:"",
       description:"",
       plant:"",
       andonDisplay:"",
       depthMaterial:"",
       supplyLine: "",
       uom:"",
       createdBy: "",
       createdDate: "",
       changedBy: "",
       changedDate: "",
    },
    {
       materialNo:"",
       description:"",
       plant:"",
       andonDisplay:"",
       depthMaterial:"",
       supplyLine: "",
       uom:"",
       createdBy: "",
       createdDate: "",
       changedBy: "",
       changedDate: "",
    },
    {
       materialNo:"",
       description:"",
       plant:"",
       andonDisplay:"",
       depthMaterial:"",
       supplyLine: "",
       uom:"",
       createdBy: "",
       createdDate: "",
       changedBy: "",
       changedDate: "",
    },
]